Programs events
blackberggroup/VA-DOE pull request #3
Opened 2023-08-16 15:05 UTC by ronald-wbd

I created a new programs section here that includes the masthead and a placeholder for the news section to fill in above and below elements for svg animation to work. My new branch will be named news-carousel to include the carousel + json data feed.

2023-08-18 14:09 UTC, will-wbd requested changes
There is a width issue on larger screens. See screenshot
![widescreen-width](https://github.com/WBDynamics/VA-DOE/assets/134664107/e5fb7e3e-c002-405c-aa61-7e3835da0909)

Let's get that going first

2023-08-18 14:55 UTC, ronald-wbd commented
hi team! you can checkout the new branch (should match layout at https://victorious-forest-0afabf510-3.centralus.3.azurestaticapps.net/) with:

git checkout remotes/origin/programs-events

pending large screen sizes fix...

2023-08-18 16:44 UTC, ronald-wbd commented
made layout updates for larger screen sizes - can be viewed here:

https://victorious-forest-0afabf510-3.centralus.3.azurestaticapps.net/

2023-09-26 19:36 UTC, will-wbd approved these changes

2023-09-26 20:11 UTC, merged