Feature 6156040636 webpage updates
blackberggroup/VA-DOE pull request #34
Opened 2024-03-06 18:53 UTC by RyanCrux

## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description

Multiple edits requested across three pages. Provided list can be found uploaded in "files" on the Monday ticket:
https://blackberg-group.monday.com/boards/1931719392/pulses/6156040636

Overview:

Homepage:
- Update Diffusion Talent Accelerator Innovation Spotlight with new image
- Update News & Events Carousel ( removed old and replaced [image/text/links] )
- Update Our Team Section (multiple new/updated head shots) 

shark tank page:
- Replace innovation spotlight for Surgical Pause with Contraception on Demand (image/text/links)
- Replace innovation spotlight for Beta Lactum with White Noise Project (image/text/links)
- Update News & Events Carousel ( removed old and replaced [image/text/links] )

National Diffusion Practices page:
- Update News & Events Carousel ( removed old and replaced [image/text/links] )

One remaining request about overall font size on site was handed off to Will. This was removed from the scope of this ticket at this time.

## Related Tickets & Documents
- Monday Task #6156040636

## QA Instructions, Screenshots, Recordings

review new images and check page paths. 

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

2024-03-06 19:09 UTC, RyanCrux commented
Compressed images and all checks have passed - I need one reviewer please :)

2024-03-07 14:22 UTC, will-bbg submitted a review, later dismissed
Team photos are not updated
<img width="1115" alt="Screenshot 2024-03-07 at 8 15 30 AM" src="https://github.com/blackberggroup/VA-DOE/assets/145696026/5f04565d-db40-468e-aa3d-9963604cff3a">

- News and Events are not updated
<img width="1426" alt="Screenshot 2024-03-07 at 8 20 15 AM" src="https://github.com/blackberggroup/VA-DOE/assets/145696026/e5b2d851-bc08-40f1-ae6e-850c241644fc">

Please double check that the files were uploaded to Dev-Innovation. This is also a part of the PR creation process

2024-03-07 14:22 UTC, will-bbg commented on _includes/sharktank/3-up.html
> +                <p class="font-body">o	Contraception on Demand trains pharmacy practitioners to conduct patient-centered
Weird character in the first line of the sentence.

2024-03-07 14:58 UTC, RyanCrux commented
@will-bbg fixed up the weird character and adjusted my paths correctly. I verified everything on dev-innovation.bgsandbox. Please take another pass at approving, thanks!

2024-03-08 16:47 UTC, ronald-bbg commented on _includes/sharktank/3-up.html
> +                        <a href="https://marketplace.va.gov/innovations/the-white-noise-project"><img src="../assets/img/sharktank/white-noise-project.jpg" class="img-fluid radius-lg" alt="Image of p
For alt text best practices, I would remove "Image of" and say "A person presenting..."

2024-03-08 16:48 UTC, ronald-bbg commented on _includes/sharktank/3-up.html
> +                        <a href="https://marketplace.va.gov/innovations/contraception-on-demand"><img src="../assets/img/sharktank/contraception-on-demand.jpg" class="img-fluid radius-lg" alt="Image
Can remove "Image of" and just describe who is in the photo and what they are doing

2024-03-08 16:51 UTC, ronald-bbg requested changes
Left a couple notes on alt text best practices where we can remove "Image of" and directly describe the person doing an action...for example "A person conversating with..."

2024-03-08 21:16 UTC, ronald-bbg approved these changes

2024-03-08 21:27 UTC, merged