Feature/jls 6158463071/new dta content
blackberggroup/VA-DOE pull request #35
Opened 2024-03-14 18:52 UTC by ecstech-admin

## What type of PR is this? (check all applicable)

- [x] Feature
- [ ] Bug Fix
- [ ] Hot Fix
- [ ] Optimization
- [ ] Documentation Update

## Description
Substantial content updates per Word Doc provided by Alec in Monday Task #6158463071

## Related Tickets & Documents
- Monday Task #6158463071

## QA Instructions, Screenshots, Recordings
PR for review of Diffusion Talent Accelerator page

### UI accessibility checklist
_If your PR includes UI changes, please utilize this checklist:_
- [ ] Semantic HTML implemented?
- [ ] Keyboard operability supported?
- [ ] Checked with [Google Lighthouse](https://developer.chrome.com/docs/lighthouse/overview) and addressed `Critical` and `Serious` issues?
- [ ] Color contrast tested?

## Are there any post deployment tasks we need to perform?
- Add GA code on production
- Proper meta tags utilized

2024-03-15 18:23 UTC, ronald-bbg requested changes
<img width="596" alt="Screenshot 2024-03-15 at 11 21 06 AM" src="https://github.com/blackberggroup/VA-DOE/assets/137827146/99bd310d-02a5-4881-b8aa-b3efe8051b84">
Not sure if intentional but see a faint gray border where the arrow images are placed.


<img width="772" alt="Screenshot 2024-03-15 at 11 22 22 AM" src="https://github.com/blackberggroup/VA-DOE/assets/137827146/2f2f1351-1810-4d73-a1d4-eeb93862c464">

Should we also have even margin or padding above and below the "Empower your impact section"?

2024-03-15 18:23 UTC, ronald-bbg commented on _site/diffusion-talent-accelerator/index.html
For alt text best practices, it is recommended that we don't need to mention "Photo of..." for photos. We can start for e.g. "A woman speaking..." as it satisfies descriptive text.

2024-03-15 18:23 UTC, ronald-bbg commented on diffusion-talent-accelerator/index.html
> -                            <div class="secondary-banner__tagline">Diffusion of Excellence will be recruiting Cohort 2 in January of 2024. <br />For more information, please email <a href="mailto:VAC
The copy should be updated to : Recruitment is currently closed. Applications for the next cohort will open
in January 2025. For more information, please email
VHADiffusionTalentAccelerator@VA.gov. (Alec's doc for reference)

2024-03-18 18:03 UTC, ecstech-admin commented
Updates made to PR:

- Timeline: new 508 contrast colors for backgrounds
- Timeline: add margin bottom
- Timeline: rm right-left margins
- Adjust alt tags per Ronalds' comment

2024-03-18 18:38 UTC, RyanCrux requested changes
I went though the Monday ticket Word doc line by line. 2 fixes needed. Everything else looks great Jim. 

 1) It looks like the text here is white:
<img width="1166" alt="Screenshot 2024-03-18 at 2 33 49 PM" src="https://github.com/blackberggroup/VA-DOE/assets/153299181/d859ee1b-806d-4073-b3fc-96caa29b9317">


2) Something is missing/ design does not match on the DTA timeline:
<img width="1398" alt="Screenshot 2024-03-18 at 2 34 00 PM" src="https://github.com/blackberggroup/VA-DOE/assets/153299181/96be088a-8315-4465-83b6-9c71de2a0746">

2024-03-18 18:56 UTC, RyanCrux approved these changes

2024-03-18 19:01 UTC, merged